CREATE DATABASE IF NOT EXISTS personapi;

CREATE TABLE IF NOT EXISTS person (
    id SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    cpf VARCHAR(50) NOT NULL,
    birthday DATE NOT NULL
);